const settingsActionTypes =  {    
    SWITCH_TAB: "SWITCH_TAB",
    RETRIEVED_SETTINGS: "RETRIEVED_SETTINGS",
    UPDATED_SETTINGS: "UPDATED_SETTINGS",
    UPDATED_PROFILEMAPPING: "UPDATED_PROFILEMAPPING",
    SETTINGS_CLIENT_MODIFIED: "SETTINGS_CLIENT_MODIFIED",
    RETRIEVED_PROFILESETTINGS: "RETRIEVED_PROFILESETTINGS",
    RETRIEVED_PROFILEPROPERTIES: "RETRIEVED_PROFILEPROPERTIES",
    CANCELLED_PROFILEMAPPING_CLIENT_MODIFIED: "CANCELLED_PROFILEMAPPING_CLIENT_MODIFIED",
    PROFILEMAPPINGS_CLIENT_MODIFIED: "PROFILEMAPPINGS_CLIENT_MODIFIED",
    SWITCH_MAPPING_SUBTAB: "SWITCH_MAPPING_SUBTAB",
    RETRIEVED_ROLEMAPPINGSETTINGS: "RETRIEVED_ROLEMAPPINGSETTINGS",
    RETRIEVED_AVAILABLEROLES: "RETRIEVED_AVAILABLEROLES",
    ROLEMAPPINGS_CLIENT_MODIFIED: "ROLEMAPPINGS_CLIENT_MODIFIED",
    RETRIEVED_USERMAPPINGSETTINGS: "RETRIEVED_USERMAPPINGSETTINGS",
    USERMAPPINGS_CLIENT_MODIFIED: "USERMAPPINGS_CLIENT_MODIFIED"
};
export default settingsActionTypes;